name: UserKeyboardShortcuts
author: re5et
category: Utilities
tags: [keyboard, shortcuts, localStorage, Cookie]
docs: http://github.com/re5et/UserKeyboardShortcuts
demo: http://re5et.github.com/projects/userKeyboardShortcuts/demo/
current: 0.1